---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-external-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}-external
  {{ end }}
{{ file .INGRESS_EXTERNAL_ANNOTATIONS | indent 2 }}
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - {{ .DRONE_BUILD_NUMBER }}.internal.sas-lmr-branch.homeoffice.gov.uk
        - lmr-{{ .DRONE_SOURCE_BRANCH }}.internal.sas-lmr-branch.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
        - lmr.uat.sas-notprod.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
        - {{ .PRODUCTION_URL }}
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: branch-tls-external
      {{ else }}
      secretName: cert-cmio
      {{ end }}
      
  rules:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: lmr-{{ .DRONE_SOURCE_BRANCH }}.internal.sas-lmr-branch.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - host: lmr.uat.sas-notprod.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
    - host: {{ .PRODUCTION_URL }}
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
              {{ else }}
              serviceName: {{ .APP_NAME }}
              {{ end }}
              servicePort: 10443
