apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: branch-tls-internal
  labels:
    cert-manager.io/solver: http01
spec:
  commonName: "*.sas-lmr-branch.homeoffice.gov.uk"
  dnsNames:
  - "*.sas-lmr-branch.homeoffice.gov.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: branch-tls-internal
