export const ConstantsLib = {
  // ECS TEST DATA
  FULL_NAME: 'HOF TEST',
  DOB_11_11_1988: '11/11/1988',
  NATIONALITY_NIGER: 'Niger',
  ADDRESS_LINE_1: '100',
  ADDRESS_LINE_2: 'Tenth St',
  TOWN_OR_CITY: 'HULL',
  ZIP_CODE: '123456',
  LOCATION_Algeria: 'Algeria',
  POSTCODE: 'M11 1HH',
  COUNTRY_UK: 'United Kingdom',

  REGISTRATION_CARD_NO: 'ZU1234567',
  RESPONSE_NONE_OF_THE_ABOVE: 'None of the above',
  B_ADDRESS_LINE_1: '89',
  B_ADDRESS_LINE_2: 'HOF St',
  B_TOWN_OR_CITY: 'Leeds',
  B_POSTCODE: 'L22 2LL',
  BUSINESS_OR_COMPANY_NAME: 'HOF LTD',
  TYPE_BUSINESS: 'TECH',
  CONTACT_NAME: 'TLT HOF',
  CONTACT_JOB_TITLE: 'Business Tester',
  TELEPHONE: '01616699548',
  SAS_HOF_EMAIL: 'sas-hof-test@digital.homeoffice.gov.uk',
  HO_REF_NUMBER: '123456789',

  // LCS TEST DATA
  TENANTS_MOVE_IN_DATE: '11/11/2015',
  REF_NUMBER: 'ZW9005196',
  TENANTS_FULL_NAME: 'HOF Tenant',
  LAND_LORD_AGENT_NAME: 'HOF LandLord Agent',
  LANDLORD_NAME: 'HOF LandLord',
  COMPANY_NAME: 'Test UK Ltd',
  DOB_BEFORE_1988_1960: '01/01/1960',
  DOB_AFTER_1988_1989: '01/01/1989',
  DATE_TENANT_MOVE_TO_UK_1978: '01/01/1978',
  DOB_1978: '01/01/1978',
  B_COUNTY: 'Salford',
  PLACE_OF_BIRTH: 'London',
  NATIONAL_INSURANCE_NO: 'OK013581D',
  NATIONALITY: 'Spain',
  TENANTS_EMAIL: 'Tenants.TestEmail@digital.homeoffice.gov.uk',
  CONTACT_TELEPHONE: '01616699548',
  CONTACT_EMAIL_ADDRESS: 'sas-hof-test@digital.homeoffice.gov.uk',
  LANDLORD_EMAIL: 'Landlord.TestEmail@digital.homeoffice.gov.uk',
  AGENT_EMAIL: 'Agents.TestEmail@digital.homeoffice.gov.uk',

  // Date constants
  TODAY_S_DATE: "today's date",
  TOMORROW_S_DATE: "tomorrow's date",
  YESTERDAY_S_DATE: "yesterday's date",
} as const;