name: Building and scanning Yarn Package

on:
    pull_request:
        branches:
            - main
            - CCL-*
    push:
        branches:
            - main
            - CCL-*

jobs:
    setup:
        name: setup
        runs-on: ubuntu-latest
        env:
            NOTIFY_KEY: USE_MOCK
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run postinstall
              run: yarn run postinstall

    linting:
        name: linting
        needs: setup
        runs-on: ubuntu-latest
        env:
            NOTIFY_KEY: USE_MOCK
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Lint
              run: yarn run test:lint

    unit_tests:
        name: unit_tests
        needs: setup
        runs-on: ubuntu-latest
        env:
            NOTIFY_KEY: USE_MOCK
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Unit tests
              run: yarn run test:unit

    validation:
        needs: setup
        uses: Home-Office-Digital/core-cloud-workflow-node-yarn-actions/.github/workflows/validation.yml@1.3.1
        with:
            working_directory: "."
            node_version: "24"
            audit_level: "low"
            post_install_script: ""

    build-publish:
        needs: setup
        uses: Home-Office-Digital/core-cloud-workflow-node-yarn-actions/.github/workflows/build-publish.yml@1.3.1
        with:
            working_directory: "."
            node_version: "24"
            should_publish: false
            registry_url: ""
